[package]
name = "cwc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0"
chrono = "0.4"
owo-colors = "3.5.0"

[[bin]]
name = "cwc"
path = "src/main.rs"

